### ISSUE TITLE
CSS link doesnt work

### ISSUE THREAD

**Issue by CheesusChrist15** [EnderDragonEP/Transparent-Discord-Theme#1]
I had to copy the css source from github, i think the url in the theme file is faulty

**Comment by EnderDragonEP** [comment]
I update the  import URL. Please replace the this line:
```
@import url(https://raw.githubusercontent.com/EnderDragonEP/Transparent-Discord-Theme/main/css/source.css);
```

to this:
```
@import url(https://enderdragonep.github.io/Transparent-Discord-Theme/css/source.css);
```
or download the new theme file from my GitHub repo.
Let me know if you have further questions!
